### ISSUE TITLE
Official Gnusocial site

### ISSUE THREAD

**Issue by aab3r** [foocorp/fedi.network#1]
Hi!

I've found two references that point at https://gnusocial.network as the current official site. While this was true for a while (I think during v2 development), the new official site nowadays is https://www.gnusocial.rocks/, as you can check in nodeinfo from any up-to-date GS site (for instance, https://gnusocial.net/api/nodeinfo/2.0.json )

Those are the places where I've found the references:

https://github.com/foocorp/fedi.network/blob/67368dad6f630729a0654ed2a6ace10da14cb52a/social.html#L48
https://github.com/foocorp/fedi.network/blob/67368dad6f630729a0654ed2a6ace10da14cb52a/moved.html#L50

Thanks for the redirections, by the way!

**Comment by mattl** [comment]
https://github.com/foocorp/fedi.network/commit/aa218ebdb83c63c3332cc907e56c397a3a8eac66 fixes this.
